# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: KeeAnywhere
email: daniel@boelts.de
description: >- # this means to ignore newlines until "baseurl:"
  A cloud storage provider plugin for KeePass Password Safe
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://keeanywhere.de" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: 
github_username:  kyrodan

collections:
  use:
    output: true
    order:
      - start
      - installation.md
      - first_use.md
      - advanced_topics.md
      - troubleshooting.md
      - url_specification.md
      - faq.md

defaults:
  - scope:
      path: ""
      type: "use"
    values:
      layout: "usage"
      description: Usage Guide
  - scope:
      path: ""
    values:
      layout: "default"

# Build settings
markdown: kramdown
plugins:
#  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- CNAME