name: Linux build

on:
#  push:
#    branches: master
  workflow_dispatch:

env:
  version: 2.1.0

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
